CREATE TABLE `data_platform_article_header_data`
(
  `Article`                          int(16) NOT NULL,
  `ArticleType`                      varchar(4) NOT NULL,
  `ArticleOwner`                     int(12) NOT NULL,
  `ArticleOwnerBusinessPartnerRole`  varchar(40) NOT NULL,
  `PersonResponsible`                varchar(40) NOT NULL,
  `ValidityStartDate`                date NOT NULL,
  `ValidityStartTime`                time NOT NULL,
  `ValidityEndDate`                  date NOT NULL,
  `ValidityEndTime`                  time NOT NULL,
  `OperationStartDate`               date NOT NULL,
  `OperationStartTime`               time NOT NULL,
  `OperationEndDate`                 date NOT NULL,
  `OperationEndTime`                 time NOT NULL,
  `Description`                      varchar(60) NOT NULL,
  `LongText`                         varchar(1000) NOT NULL,
  `Introduction`                     varchar(200) DEFAULT NULL,
  `Site`                             int(16) NOT NULL,
  `Project`                          int(16) DEFAULT NULL,
  `WBSElement`                       int(8) DEFAULT NULL,
  `Tag1`                             varchar(40) DEFAULT NULL,
  `Tag2`                             varchar(40) DEFAULT NULL,
  `Tag3`                             varchar(40) DEFAULT NULL,
  `Tag4`                             varchar(40) DEFAULT NULL,
  `DistributionProfile`              varchar(4) NOT NULL,
  `QuestionnaireType`                varchar(4) DEFAULT NULL,
  `QuestionnaireTemplate`            varchar(4) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `CreateUser`                       int(12) NOT NULL,
  `LastChangeUser`                   int(12) NOT NULL,
  `IsReleased`                       tinyint(1) DEFAULT NULL,
  `IsCancelled`                      tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Article`),

    CONSTRAINT `DPFMArticleHeaderDataArticleType_fk` FOREIGN KEY (`ArticleType`) REFERENCES `data_platform_article_type_article_type_data` (`ArticleType`),
    CONSTRAINT `DPFMArticleHeaderDataArticleOwner_fk` FOREIGN KEY (`ArticleOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMArticleHeaderDataArticleOwnerBPRole_fk` FOREIGN KEY (`ArticleOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMArticleHeaderDataSite_fk` FOREIGN KEY (`Site`) REFERENCES `data_platform_site_header_data` (`Site`),
    CONSTRAINT `DPFMArticleHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMArticleHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMArticleHeaderDataDistributionProfile_fk` FOREIGN KEY (`DistributionProfile`) REFERENCES `data_platform_distribution_profile_distribution_profile_data` (`DistributionProfile`),
    CONSTRAINT `DPFMArticleHeaderDataQuestionnaireType_fk` FOREIGN KEY (`QuestionnaireType`) REFERENCES `data_platform_questionnaire_type_questionnaire_type_data` (`QuestionnaireType`),
    CONSTRAINT `DPFMArticleHeaderDataQuestionnaireTemplate_fk` FOREIGN KEY (`QuestionnaireTemplate`) REFERENCES `data_platform_questionnaire_tmpl_questionnaire_tmpl_data` (`QuestionnaireTemplate`),
    CONSTRAINT `DPFMArticleHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMArticleHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
